---
- name: Check if settings.local.php is in place.
  command: ls "{{ drupal_core_path }}/sites/default/settings.local.php"
  changed_when: false
  failed_when: false
  register: settings_local_installed

- name: Copy settings.local.php into place.
  shell: >
    cp "{{ drupal_composer_install_dir }}/scripts/seed/settings.local.php" "{{ drupal_core_path }}/sites/default/settings.local.php"
    creates="{{ drupal_core_path }}/sites/default/settings.local.php"
  when: settings_local_installed | failed
  become: yes
  become_user: "{{ composer_home_owner }}"

- name: Check if services.local.yml is in place.
  command: ls "{{ drupal_core_path }}/sites/default/services.local.yml"
  changed_when: false
  failed_when: false
  register: services_local_installed

- name: Copy services.local.yml into place.
  shell: >
    cp "{{ drupal_composer_install_dir }}/scripts/seed/services.local.yml" "{{ drupal_core_path }}/sites/default/services.local.yml"
    creates="{{ drupal_core_path }}/sites/default/services.local.yml"
  when: services_local_installed | failed
  become: yes
  become_user: "{{ composer_home_owner }}"
